server:
  port: 8080

spring:
  application:
    name: infrastructure-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-member
          uri: lb://service-member
          predicates:
            - Path=/api/members/**
          filters:
            - StripPrefix=2
        - id: service-payment
          uri: lb://service-payment
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2
        - id: service-content
          uri: lb://service-content
          predicates:
            - Path=/api/contents/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
